### ISSUE TITLE
Free Text Field for Registration form

### ISSUE THREAD

**Issue by hno2** [byro/byro#103]
Hey there, 
I really love this project.
I couldn't find this feature, but I might be just stupid: Is there any way to add fields to the Registration form and if so how?
For my organization e.g. we need to ask for the University of a Member (but if the member does not have a university this field is empty)

I guess I can add this here?https://github.com/byro/byro/blob/c48db4f520a0513a480eeda341147aa462acfbf0/src/byro/plugins/profile/models.py#L8-L18
But a way to add this in the frontend would be fabulous.
Many thanks in advance!

**Comment by rixx** [comment]
The intended way of modifying byro is by creating a plugin, where you can add arbitrary fields and will not run into problems regarding updates. You can find a guide in our docs! https://byro.readthedocs.io/en/latest/developer/plugins/
