### ISSUE TITLE
Setting Language does not work.

### ISSUE THREAD

**Issue by hno2** [byro/byro#104]
When I try to change the language to german in the frontend everything is still displayed in english. Same thing when using the sample data. 

`python manage.py compilemessages` was done before and worked, I tried restarting the server and logging out - No change.

**Comment by henryk** [comment]
Hmm, I'm not entirely sure what the "Language" selector in the frontend does (@rixx ?), but what does work is changing the language in the `local_settings.py':

````
LANGUAGE_CODE="de"
````

**Comment by ilu33** [comment]
"You are using the deprecated local_settings.py – Please move to the byro.cfg format"
It seems that  this needs to be put in byro.cfg
```
[locale]
language_code = de
time_zone =`Europe/Berlin 
```

**Comment by benediktg** [comment]
When there is `django.middleware.locale.LocaleMiddleware` loaded between the SessionMiddleware and the CommonMiddleware, Django normally detects the right localisation based on the user preference in the browser:
https://docs.djangoproject.com/en/4.0/topics/i18n/translation/

**Comment by rixx** [comment]
`language_code` has been documented in the administrator configuration documentation.
