### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by hdznrrd** [byro/byro#108]
Tried setting up byro using the supplied docker-compose.yml simply using "docker-compose up":

```
[...]
Removing intermediate container 15730aea4f25
 ---> 782db28fe948
Step 10/19 : ADD requirements.txt /opt/code/requirements.txt
ERROR: Service 'web' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder625060417/requirements.txt: no such file or directory
```

**Comment by rixx** [comment]
Yeah, sorry, the docker-compose.yml isn't really supported at this point. We switched to a package-based installation process, so in some way ``pip install -r requirements.txt`` will have to be replaced by ``pip install -e .`` in the directory containing the ``setup.py``.
