### ISSUE TITLE
not a git repository during createsuperuser

### ISSUE THREAD

**Issue by MoritzFago** [byro/byro#125]
During the creation of the superuser, as per the official administrator documentation, there is an error about not beeing in a git repository.
Command: `sudo -iu byro python3 -m byro createsuperuser`
OS: `Debian GNU/Linux 10 (buster)`
Expected result:
No error

Actual result:
```
[...]
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
Superuser created successfully.
```

**Comment by rixx** [comment]
Thanks for the report!
