### ISSUE TITLE
How to register plugins in production

### ISSUE THREAD

**Issue by MoritzFago** [byro/byro#126]
I tried to install some plugins, but they don't show up in byro.
I just installed them with pip, is there anything else I have to do?
OS: Debian 10
My setup: https://github.com/MoritzFago/ansible-byro

**Comment by rixx** [comment]
Hm, installing them should do the trick, not sure why it wouldn't. Shouldn't matter if they come from GitHub or not, either. We're using the pip entrypoint system that should be used in any case. The plugins are not listed at startup time, I assume?

You can try running ``python setup.py develop`` in the repo checkouts instead, and check if that helps?

**Comment by MoritzFago** [comment]
User error, I installed the plugins in a different user. Works if used correctly.
