### ISSUE TITLE
Allow creation of additional member fields

### ISSUE THREAD

**Issue by MoritzFago** [byro/byro#127]
Every association is different.
For exampe, during our evaluation for the Toppoint e.V we found that we need some additional fields.
We allow members under the age of 18. German law requires a supervising adult (Gesetzlicher Vertreter) for the membership and we need to track that.
It would be nice, if this wouldn't require to write a byro-$association_name plugin. Or is this expected?

**Comment by rixx** [comment]
Yeah, it's expected that this needs a plugin, and is the primary reason plugins exist at all. I'm afraid generating database migrations on the fly within byro isn't something we can do with reasonable effort and compatibility.
