### ISSUE TITLE
How could non-€ configs be approached?

### ISSUE THREAD

**Issue by dnet** [byro/byro#222]
Although there's a `Configuration` attribute called `currency` for setting the 3-letter currency code (such as `EUR`), almost every user-facing view has the symbol `€` hardcoded. Before touching anything any submitting PRs, I wanted to ask what you think about this. Could all these instances be replaced by the three letter currency code? Or should I add another configuration value for a pretty-printed currency symbol?

Another related thing is the number of decimal places, since exchange rates result in some non-€ currencies not using decimal fractions at all. Would you accept such a PR that would make the number of decimal fraction digits configurable as well?

**Comment by rixx** [comment]
To handle this correctly, we'd need several settings:

- currency (already there)
- currency_symbol
- currency_symbol_position (before/after)
- decimal places

Though acceptable decimal places could only be 0,1,2 unless we want to add a database migration. A PR implementing this would of course be welcome.
