### ISSUE TITLE
Production instllation not rendering correctly

### ISSUE THREAD

**Issue by karl-baker** [byro/byro#318]
Hello,

After locally installing Byro for a production system on Ubuntu 22.04 Desktop running on a Dell notebook it appear to not render correctly.  Please see attached screenshot.

What do I need to do to fix this?

Thanks.

![Bildschirmfoto vom 2023-03-19 15-46-21](https://user-images.githubusercontent.com/31621108/226184035-fbf3c801-b17d-48fd-aeca-9794d5bba431.png)

**Comment by rixx** [comment]
Seems like you are not serving your static files correctly – though we should probably just use `whitenoise` and have byro do it at this point, because why not.
