### ISSUE TITLE
Byro Installation using whitenoise

### ISSUE THREAD

**Issue by karl-baker** [byro/byro#326]
Hello,

I have completely reinstalled Ubuntu 22.04. on a Dell notebook, and have installed byro only for use locally on this machine.  Generally, the machine will neither be in a local network nor will it be online in the internet. Both the LAN and WiFi connections will be turned off, and WiFi will only be turned on should I need access for troubleshooting remotely.  Therefore, as byro will only be running locally SSL is not needed.  In addition, whitenoise has been installed in order to access the static files.  The web server for byro being used is nginx.

Based on the installation instructions provided I have setup a default server in /etc/nginx/sites-enabled/default using this configuration:

`
server {
    listen 80 default_server;
    #listen [::]:80 ipv6only=on default_server;
    server_name byro.local.org;

    add_header Referrer-Options same-origin;
    add_header X-Content-Type-Options nosniff;

    location / {
        proxy_pass http://localhost:8345/;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
    }

    location /media/ {
        alias /var/byro/data/media/;
        add_header Content-Disposition 'attachment; filename="$1"';
        expires 7d;
        access_log off;
    }
}
`

The nginx service appears to be happy with this configuration and does not complain:

`
$ sudo systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-13 23:18:46 CEST; 17min ago
       Docs: man:nginx(8)
    Process: 4792 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 4793 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
   Main PID: 4794 (nginx)
      Tasks: 5 (limit: 9230)
     Memory: 4.8M
        CPU: 29ms
     CGroup: /system.slice/nginx.service
             ├─4794 "nginx: master process /usr/sbin/nginx -g daemon on; master_process on;"
             ├─4795 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─4796 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─4797 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             └─4798 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""

Jun 13 23:18:46 vlm-byro-01 systemd[1]: Starting A high performance web server and a reverse proxy server...
Jun 13 23:18:46 vlm-byro-01 systemd[1]: Started A high performance web server and a reverse proxy server.
`

The /etc/byro/byro.cfg file has this setup:

`
[filesystem]
data = /var/byro/data
media = /var/byro/data/media
logs = /var/byro/data/logs

[locale]
language_code = de

[site]
debug = False
url = http://byro.local.org
#url = localhost:8345

[database]
name = byro
user = byro
password = byro
host = localhost
port = 5432
engine = postgresql

[mail]
from = admin@localhost
host = localhost
port = 25
user = admin
password = something
tls = False
ssl = True
`

Byro appears to start/restart without complaining:

`
$ sudo systemctl status byro-web
● byro-web.service - byro web service
     Loaded: loaded (/etc/systemd/system/byro-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-13 23:43:32 CEST; 1s ago
   Main PID: 5177 (gunicorn)
      Tasks: 5 (limit: 9230)
     Memory: 215.6M
        CPU: 2.589s
     CGroup: /system.slice/byro-web.service
             ├─5177 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             ├─5180 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             ├─5181 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             ├─5182 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             └─5185 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345

Jun 13 23:43:33 vlm-byro-01 gunicorn[5182]: ┃                                                                         ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5182]: ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┃ ┏━o━━━━o━━━┓ This is byro v0.0.2 calling, running in production mode.   ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┃ ┣━━━o━━━o━━┫                                                            ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┃ ┣━━━━━━━━━━┫ Settings:                                                  ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┃ ┃   byro   ┃ Read from: /etc/byro/byro.cfg                              ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┃ ┗━━━━━━━━━━┛ Logging:   /var/byro/data/logs                             ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┃                                                                         ┃
Jun 13 23:43:33 vlm-byro-01 gunicorn[5185]: ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
`

But, when I try to access byro locally I receive a HTTP Server Error (500) and now the service complains:

`
$ sudo systemctl status byro-web
● byro-web.service - byro web service
     Loaded: loaded (/etc/systemd/system/byro-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-13 23:43:32 CEST; 9min ago
   Main PID: 5177 (gunicorn)
      Tasks: 5 (limit: 9230)
     Memory: 232.8M
        CPU: 3.551s
     CGroup: /system.slice/byro-web.service
             ├─5177 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             ├─5180 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             ├─5181 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             ├─5182 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
             └─5185 /usr/bin/python3 /var/byro/.local/bin/gunicorn byro.wsgi --name byro --workers 4 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345

Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:     return self.handle_simple(path)
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:   File "/var/byro/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 118, in handle_simple
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:     return staticfiles_storage.url(path)
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:   File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:     return self._url(self.stored_name, name, force)
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:   File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:     hashed_name = hashed_name_func(*args)
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:   File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]:     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
Jun 13 23:52:27 vlm-byro-01 gunicorn[5182]: ValueError: Missing staticfiles manifest entry for 'office/img/byro_32.png'
`

The last entry of /var/byro/data/logs/byro.log gives me the same error message:

`
$ tail -1 byro.log 
ValueError: Missing staticfiles manifest entry for 'office/img/byro_32.png'
`

Although I am not a web server administrator it does appear that nginx is (possibly suboptimal, but) properly configured, and that the issue may lie somewhere with the whitenoise configuration.  This also was setup through the examples provided for the settings.py here on github.  I would greatly appreciate some help getting things properly configured, as I would like to deliver the notebook to the organization I am working with by the end of the week.

Thank you,

Karl Baker

**Comment by rixx** [comment]
Not an nginx error – sounds like you didn't run `collectstatic`? Make sure to run `collectstatic` and `compress`, please, and then restart the service. If that doesn't fix the problem, please re-open the issue.

**Comment by karl-baker** [comment]
Receiving these exceptions when trying to run collectstatic:

`
python3 -m byro collectstatic
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━o━━━━o━━━┓ This is byro v0.0.2 calling, running in production mode.   ┃
┃ ┣━━━o━━━o━━┫                                                            ┃
┃ ┣━━━━━━━━━━┫ Settings:                                                  ┃
┃ ┃   byro   ┃ Read from: /etc/byro/byro.cfg                              ┃
┃ ┗━━━━━━━━━━┛ Logging:   /var/byro/data/logs                             ┃
┃                                                                         ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

You have requested to collect static files at the destination
location as specified in your settings:

    /var/byro/.local/lib/python3.10/site-packages/static.dist

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Post-processing 'vendored/jquery-ui/jquery-ui.min.css' failed!

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/byro/.local/lib/python3.10/site-packages/byro/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'vendored/jquery-ui/images/ui-icons_444444_256x240.png' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fb2acff5750>.

The CSS file 'vendored/jquery-ui/jquery-ui.min.css' references a file which could not be found:
  vendored/jquery-ui/images/ui-icons_444444_256x240.png

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.

`
