### ISSUE TITLE
Using Pipenv for dependencies

### ISSUE THREAD

**Issue by mraerino** [byro/byro#34]
I was wondering if there were plans to switch from `requirements.txt` files to the new and much improved dependency handling principle with a `Pipfile` through [Pipenv](http://pipenv.readthedocs.io/en/latest/)

### Gains
- Automatic virtualenv handling
  - `pipenv install` to create and install dependencies
  - `pipenv shell` to activate
  - `pipenv run <cmd>` to run something inside
- Seperate Lockfile (`Pipfile.lock`)
- Unified production and development dependencies

**Comment by rixx** [comment]
For this we'd need to figure out how to register plugins with `pipenv`, I don't know how this would work with pipenv.

Also, side note: Production and development dependencies to be "unified" isn't an advantage I'd see as such – I need different things in development than I need in production.

**Comment by mraerino** [comment]
> For this we'd need to figure out how to register plugins with pipenv, I don't know how this would work with pipenv.

What mechanism is currently used to register/install plugins?

I'm also not sure about the recommended way to install for people, who want to use the software, but I'll probably create another issue for questions around this topic.

> Production and development dependencies to be "unified" isn't an advantage I'd see as such – I need different things in development than I need in production.

Pipenv uses sections inside the `Pipfile` to seperate production and development dependencies. But they're in one file. Per default only production dependencies get installed.

**Comment by rixx** [comment]
> Pipenv uses sections inside the Pipfile to seperate production and development dependencies. But they're in one file. Per default only production dependencies get installed.

I don't see a fundamental advantage in having a production.txt and development.txt vs one file – at least not significant enough to make me switch packaging tools. I'd still like to see how pipenv adoption will develop in the Python world.

> What mechanism is currently used to register/install plugins?

You call `python setup.py develop`, for now.

> I'm also not sure about the recommended way to install for people, who want to use the software, but I'll probably create another issue for questions around this topic.

Well, this depends on your environment, requirements, experience, and a host of other things. The options are the provided docker setup and the plain python setup.

**Comment by rixx** [comment]
Closing this for now, as I don't recognise it as an actual *issue* with byro. If somebody PRs a pipfile here and in the plugin cookiecutter repository that works with our plugin system, I'll happily merge it.
