### ISSUE TITLE
Use GPG

### ISSUE THREAD

**Issue by rixx** [byro/byro#43]
I'm not sure if GPG integration should be a plugin or a core feature – probably a vendored plugin would be best, that could be turned off or on, but will be shipped with byro automatically.

This issue includes key management for members, sending out emails to those members encrypted if they wish, and lots and lots of error handling.

**Comment by vollkorn1982** [comment]
Error handling would mean sending an unencrypted email with an appropriate message to resolve this issue to the recipient in place of the email that was originally meant to send, but keep that email in the sending queue, so it can be re-sent later.

Ideally, there would be a way to verify keys, especially when a key changes, for example, by checking if the new key is signed by the old key.

PGP/MIME would be great, but is more complicated. Especially attachments with PGP/MIME are a bit complex.

Optionally, all outgoing email should be signed by the sender's key.

There are standards like [Memoryhole](https://github.com/autocrypt/memoryhole) and [autocrypt](https://autocrypt.org/), which would be quite nice to support.

**Comment by vollkorn1982** [comment]
I replaced this issue with issues #76, #77, #78, #79, and #80.
