### ISSUE TITLE
Allow to create members with no e-mail address

### ISSUE THREAD

**Issue by henryk** [byro/byro#61]
Current logic in https://github.com/byro/byro/blob/master/src/byro/office/views/members.py#L94 hardcodes an attempt to send an e-mail to the address in the `email` field in the new member form.
If that field is empty or non-present, an IntegrityError is raised, because an attempt is made to create an "EMail" model with NULL to address.

Should we either:
 * Not try to send the member welcome mail if no email address is entered?
 * Or: Put it into outbox, with some marking and default to address (vorstand?) so that it can be manually re-adressed or deleted as appropriate?

**Comment by vollkorn1982** [comment]
Other option we use in the CCC office:
* Queue that email for PDF generation and send it as a letter, if a postal address is known.

**Comment by henryk** [comment]
Ahh, that's also a good variation. What I'm currently working on is to make it possible to enter multiple points of contact per member (mostly relevant for corporate persons), which is not fully compatible with the simple new member form anyway.

I've now made it so that no e-mail is sent if no address is provided, but want to have a "(Re)send welcome e-mail" button (#62).  (Workflow: Add the corporate person with no e-mail address, add point(s) of contact, press re-send button.)

With #59 both ways to generate the welcome message could also go into snail mail.
