### ISSUE TITLE
Charge members (Lastschrift)

### ISSUE THREAD

**Issue by rixx** [byro/byro#71]
- [ ] Send email x days prior to charge
- [ ] one-time charges
- [ ] periodic charges

**Comment by danimo** [comment]
Has any work been put into this already? We need this, and can maybe assist in getting this done (cc @mhannig).

**Comment by vollkorn1982** [comment]
Ah, I know someone who offered help for this as well: Schiermi from Frankfurt. Don't know if he has a github account, though.

**Comment by vollkorn1982** [comment]
So, it seems like the way to go is exporting as SEPA/PAIN XML. @raphaelm has written a module for that: https://github.com/raphaelm/python-sepaxml Another implementation, which is available in pypi as 'sepa' and supports quite a few payment messages: https://github.com/VerenigingCampusKabel/python-sepa

Then you use some other software to import this XML and transfer it to your bank.

Alternatively, one could use FinTS, which many banks speak, to transfer the information directly: https://github.com/raphaelm/python-fints

**Comment by rixx** [comment]
Find solutions on the [plugin list](https://github.com/byro/byro/wiki/Plugins)
