### ISSUE TITLE
Empty Administrator Documentation

### ISSUE THREAD

**Issue by hno2** [byro/byro#97]
Hey, 

I want to install byro for a productive use. What is the best way to do this?
Unfortunately the Administrator Documentation [linked](https://byro.readthedocs.io/en/latest/administrator/#administrator-setup) is empty.

**Comment by rixx** [comment]
Ah, yes, we definitely should add administrator docs, apologies for the lack thereof. You should be good by following the developer documentation for the most part. Your `local_settings.py` will need to include a line with `DEBUG = False` to disable development mode (very important, never run the development mode in production!).

For nginx and service setup and the like, you might want to take a look at the [pretalx admin docs](https://docs.pretalx.org/en/latest/administrator/index.html), as pretalx is also a django project with a fairly similar structure.

**Comment by hno2** [comment]
Thanks a lot!
