### ISSUE TITLE
Proposal: member meta data structure

### ISSUE THREAD

**Issue by rixx** [byro/byro#99]
We need to save a couple of information on membership data fields, to be accessed in different places:

- In the registration form configuration, we need to know
   - All available fields
   - All used fields
   - Their order
   - If they are required
   - Their default values
- In relation to public member pages we need to know
   - If this information may be shown to other members
   - (Later, maybe: If this information may be shown to the general public)
- In member management actions, we need to know
   - If this information is outdated

To save us time and headaches, the format should be interoperable between those use cases. I suggest:

```
{
    "model": "member",  # one of 'member', 'membership', or any registered member profile
    "field": "field_name",  # A helper method will get us field types, form fields, etc
    "required": False,  # Plugins should never set fields to be required for interoperability, we handle it here instead
    "outdated_since": datetime(),  # Outdated information has a *lot* of meta information, which we should save elsewhere
    "visibility": None,  # One of None or "members"
    "default": …  # Since this format needs to be serializable, we can't just say 'A value or a callable' …
}
```

At the member level, we'll need the ``model``, ``field``, ``outdated_since``, and ``visibility`` fields.
At the organization level, we'll need the ``model``, ``field``, ``required``, and ``default`` fields.

Once we have these structures in place, all we need are some conversion methods, e.g. ``get_available_fields``, ``get_form_field(publication_level=None)``, …

**Comment by henryk** [comment]
Parts of this is why I added the Fields API https://github.com/byro/byro/commit/5a807615b65ec30e98be6b3291c3c6229293423c
It's currently used by the CSV import and export (that's why it exposes generic getters and setters for all fields), but I did intend it to be the single source of truth for the question "which fields does a 'Member' have" and properties such as "is writable".

**Comment by rixx** [comment]
Oh, sorry, I completely missed that. I just looked up what we used for the registration form, saw that there was no structure to it, and went ahead with this braindump. Never mind this, then.
